version: 2

updates:
  - package-ecosystem: "gitsubmodule"
    schedule:
        interval: "weekly"
    directory: "/"
    target-branch: "v2-main"
    open-pull-requests-limit: 2
    reviewers:
      - "pstjohn"
      - "jstjohn"
