site_name: BioNeMo Framework
site_url: https://docs.nvidia.com/bionemo-framework/
repo_url: https://github.com/NVIDIA/bionemo-fw-ea
repo_name: NVIDIA/bionemo-fw-ea

theme:
  name: "material"
  features:
    - content.code.annotate
    - navigation.tabs
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - search.suggest
    - search.highlight
    - content.code.copy
  font:
    text: NVIDIA Sans
    code: Roboto Mono
  favicon: assets/images/favicon.png
  logo: assets/images/logo-white.svg
  language: en
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: nvidia-light
      primary: custom
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: nvidia-dark
      primary: custom
      accent: lime
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference

extra_css:
  - assets/css/color-schemes.css
  - assets/css/fonts.css
  - assets/css/custom-material.css

plugins:
  - search
  - gen-files:
      scripts:
        - scripts/gen_ref_pages.py
  - mkdocstrings:
      handlers:
        python:
          paths:
            - ../sub-packages/*/src
  - mkdocs-jupyter

markdown_extensions:
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.snippets:
      check_paths: true
      restrict_base_path: False
      base_path: "."
  - def_list
  - admonition

copyright: |
  &copy; Copyright 2023-2024 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
